[workspace.package]
edition = "2024"
authors = ["Francesco Ceccon", "The Wings contributors"]
repository = "https://github.com/useairfoil/wings"
license = "Apache-2.0"

[workspace]
resolver = "2"
default-members = ["wings"]
members = [
    "wings",
    "wings_client",
    "wings_flight",
    "wings_ingestor_core",
    "wings_ingestor_http",
    "wings_control_plane",
    "wings_object_store",
    "wings_observability",
    "wings_server_core",
    "wings_stress",
]

[profile.maxperf]
inherits = "release"
codegen-units = 1
lto = "fat"
incremental = false

[workspace.dependencies]
arrow = "56.2.0"
arrow-flight = { version = "56.2.0", features = ["flight-sql"] }
arrow-ipc = "56.2.0"
arrow-json = "56.2.0"
arrow-schema = "56.2.0"
async-stream = "0.3.6"
async-trait = "0.1.88"
axum = "0.8.4"
base64 = "0.22.1"
bytes = "1.0"
bytesize = "2.0.1"
clap = { version = "4.5.40", features = [
    "derive",
    "env",
    "cargo",
    "unicode",
    "color",
    "unstable-styles",
] }
ctrlc = { version = "3.4.7", features = ["termination"] }
dashmap = "6.1.0"
datafusion = "50.0.0"
duration-str = "0.17.0"
flatbuffers = "25.2.10"
futures = "0.3.31"
futures-util = "0.3.31"
http = "1.3.1"
http-body = "1.0.1"
moka = { version = "0.12.10", features = ["future"] }
object_store = "0.12.2"
opentelemetry = "0.31.0"
opentelemetry-otlp = { version = "0.31.0", features = ["trace", "metrics", "grpc-tonic"] }
opentelemetry_sdk = { version = "0.31.0", features = ["trace", "metrics", "rt-tokio", "experimental_metrics_custom_reader"] }
parquet = "56.2.0"
paste = "1.0.15"
pin-project = "1.1.10"
prost = "0.13.1"
prost-types = "0.13.1"
reqwest = { version = "0.11", features = [
    "json",
    "rustls-tls",
], default-features = false }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
snafu = "0.8.0"
time = { version = "0.3.44", features = ["formatting"] }
tonic = "0.13.1"
tonic-reflection = "0.13.1"
tonic-build = "0.13.1"
tokio = { version = "1.45.1", features = ["full", "rt-multi-thread"] }
tokio-stream = "0.1.17"
tokio-util = { version = "0.7.15", features = ["time"] }
tower = "0.5"
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = [
    "std",
    "env-filter",
    "json",
] }
url = "2.5.4"
