[workspace.package]
edition = "2024"
authors = ["Francesco Ceccon", "The Wings contributors"]
repository = "https://github.com/useairfoil/wings"
license = "Apache-2.0"

[workspace]
resolver = "2"
default-members = ["wings"]
members = [
    "wings",
    "wings_client",
    "wings_flight",
    "wings_ingestor_core",
    "wings_ingestor_http",
    "wings_control_plane",
    "wings_observability",
    "wings_server_core",
    "wings_stress",
    "wings_worker",
]

[profile.maxperf]
inherits = "release"
codegen-units = 1
lto = "fat"
incremental = false

[workspace.dependencies]
arrow = "57.0.0"
arrow-flight = { version = "57.0.0", features = ["flight-sql"] }
arrow-ipc = "57.0.0"
arrow-json = "57.0.0"
arrow-schema = "57.0.0"
async-stream = "0.3.6"
async-trait = "0.1.88"
axum = "0.8.4"
base64 = "0.22.1"
bytes = "1.0"
bytesize = "2.0.1"
clap = { version = "4.5.40", features = [
    "derive",
    "env",
    "cargo",
    "unicode",
    "color",
    "unstable-styles",
] }
ctrlc = { version = "3.4.7", features = ["termination"] }
dashmap = "6.1.0"
datafusion = "52.1.0"
deltalake-aws = "0.13.0"
deltalake-core = "0.30.1"
duration-str = "0.17.0"
flatbuffers = "25.2.10"
futures = "0.3.31"
futures-util = "0.3.31"
http = "1.3.1"
http-body = "1.0.1"
iceberg = "0.8.0"
moka = { version = "0.12.10", features = ["future"] }
object_store = { version = "0.12.2", features = ["aws", "azure", "gcp"] }
opentelemetry = "0.31.0"
opentelemetry-otlp = { version = "0.31.0", features = ["trace", "metrics", "grpc-tonic"] }
opentelemetry_sdk = { version = "0.31.0", features = ["trace", "metrics", "rt-tokio", "experimental_metrics_custom_reader"] }
parquet = "57.0.0"
paste = "1.0.15"
pin-project = "1.1.10"
prost = "0.14.1"
prost-types = "0.14.1"
reqwest = { version = "0.11", features = [
    "json",
    "rustls-tls",
], default-features = false }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
snafu = "0.8.0"
tempfile = "3.0"
time = { version = "0.3.44", features = ["formatting"] }
tonic = "0.14.2"
tonic-reflection = "0.14.2"
tonic-prost = "0.14.2"
tonic-prost-build = "0.14.2"
tokio = { version = "1.45.1", features = ["full", "rt-multi-thread", "test-util"] }
tokio-stream = "0.1.17"
tokio-util = { version = "0.7.15", features = ["time"] }
tower = "0.5"
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = [
    "std",
    "env-filter",
    "json",
] }
ulid = "1.2.1"
uuid = "1.19.0"
url = "2.5.4"
