name: CD Release Pipeline

concurrency:
  group: cd-${{ github.ref }}
  cancel-in-progress: true

on:
  release:
    types: [published]

jobs:
  extract-version:
    name: "Extract release version"
    runs-on: ubuntu-latest
    outputs:
      major: ${{ steps.extract.outputs.major }}
      minor: ${{ steps.extract.outputs.minor }}
      patch: ${{ steps.extract.outputs.patch }}
      prerel: ${{ steps.extract.outputs.prerel }}
    steps:
      - name: Set $USER if needed
        run: |
          if [ -z "$USER" ]; then
            echo "USER=runner" >> "$GITHUB_ENV"
          fi
      - uses: actions/checkout@v6
      - run: mkdir -p $HOME
      - uses: cachix/install-nix-action@v30
        with:
          nix_path: nixpkgs=channel:nixos-25.11
      - uses: cachix/cachix-action@v15
        with:
          name: airfoil-public
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - id: extract
        run: nix develop .#ci --accept-flake-config -c extract-version-from-ref

  release:
    name: "wings: Release"
    needs: extract-version
    uses: ./.github/workflows/cd-release.yml
    with:
      major: ${{ needs.extract-version.outputs.major }}
      minor: ${{ needs.extract-version.outputs.minor }}
      patch: ${{ needs.extract-version.outputs.patch }}
      prerel: ${{ needs.extract-version.outputs.prerel }}
    secrets:
      cachix-token: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      quay-username: "${{ secrets.QUAY_USERNAME }}"
      quay-password: "${{ secrets.QUAY_PASSWORD }}"
