name: CD Release Pipeline

concurrency:
  group: cd-${{ github.ref }}
  cancel-in-progress: true

on:
  release:
    types: [published]

jobs:
  build-linux-x86_64:
    name: "Binary x86_64: Build"
    uses: ./.github/workflows/build.yml
    with:
      os: warp-ubuntu-latest-x64-8x
      target: default
      artifact_name: "wings-x86_64-linux.tar.gz"
    secrets:
      cachix-token: "${{ secrets.CACHIX_AUTH_TOKEN }}"

  build-linux-aarch64:
    name: "Binary aarch64: Build"
    uses: ./.github/workflows/build.yml
    with:
      os: warp-ubuntu-latest-arm64-8x
      target: default
      artifact_name: "wings-aarch64-linux.tar.gz"
    secrets:
      cachix-token: "${{ secrets.CACHIX_AUTH_TOKEN }}"

  build-image-linux-x86_64:
    name: "Docker x86_64: Build"
    uses: ./.github/workflows/build.yml
    needs: [build-linux-x86_64]
    with:
      os: warp-ubuntu-latest-x64-8x
      target: image
      artifact_name: "docker-x86_64-linux.tar.gz"
    secrets:
      cachix-token: "${{ secrets.CACHIX_AUTH_TOKEN }}"

  build-image-linux-aarch64:
    name: "Docker aarch64: Build"
    uses: ./.github/workflows/build.yml
    needs: [build-linux-aarch64]
    with:
      os: warp-ubuntu-latest-arm64-8x
      target: image
      artifact_name: "docker-aarch64-linux.tar.gz"
    secrets:
      cachix-token: "${{ secrets.CACHIX_AUTH_TOKEN }}"

  publish-docker-image:
    name: "Docker Image: Publish"
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    needs: [build-image-linux-x86_64, build-image-linux-aarch64]
    runs-on: warp-ubuntu-latest-x64-2x
    steps:
      - name: Set $USER if needed
        run: |
          if [ -z "$USER" ]; then
            echo "USER=runner" >> "$GITHUB_ENV"
          fi
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - name: "Download: x86_64 image"
        uses: actions/download-artifact@v4
        with:
          name: docker-x86_64-linux.tar.gz
          path: /tmp/x86_64
      - name: "Download: aarch64 image"
        uses: actions/download-artifact@v4
        with:
          name: docker-aarch64-linux.tar.gz
          path: /tmp/aarch64
      - run: ls /tmp/x86_64 /tmp/aarch64
      - name: Publish docker image
        run: |
          nix develop .#ci --accept-flake-config -c publish-docker-image --impure
        env:
          GHCR_USERNAME: ${{ github.actor }}
          GHCR_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
          IMAGE_ARCHIVE_x86_64: /tmp/x86_64/wings.tar.gz
          IMAGE_ARCHIVE_aarch64: /tmp/aarch64/wings.tar.gz
