name: Release wings

on:
  workflow_call:
    inputs:
      major:
        required: true
        type: string
      minor:
        required: true
        type: string
      patch:
        required: true
        type: string
      prerel:
        required: false
        type: string
    secrets:
      cachix-token:
        required: true
      quay-username:
        required: true
      quay-password:
        required: true

jobs:
  build-linux-x86_64:
    name: "Binary x86_64: Build"
    uses: ./.github/workflows/build.yml
    with:
      os: warp-ubuntu-latest-x64-8x
      target: default
      artifact_name: "wings-x86_64-linux.tar.gz"
    secrets:
      cachix-token: "${{ secrets.cachix-token }}"

  build-linux-aarch64:
    name: "Binary aarch64: Build"
    uses: ./.github/workflows/build.yml
    with:
      os: warp-ubuntu-latest-arm64-8x
      target: default
      artifact_name: "wings-aarch64-linux.tar.gz"
    secrets:
      cachix-token: "${{ secrets.cachix-token }}"

  build-image-linux-x86_64:
    name: "Docker x86_64: Build"
    uses: ./.github/workflows/build.yml
    needs: [build-linux-x86_64]
    with:
      os: warp-ubuntu-latest-x64-8x
      target: image
      artifact_name: "docker-x86_64-linux.tar.gz"
    secrets:
      cachix-token: "${{ secrets.cachix-token }}"

  build-image-linux-aarch64:
    name: "Docker aarch64: Build"
    uses: ./.github/workflows/build.yml
    needs: [build-linux-aarch64]
    with:
      os: warp-ubuntu-latest-arm64-8x
      target: image
      artifact_name: "docker-aarch64-linux.tar.gz"
    secrets:
      cachix-token: "${{ secrets.cachix-token }}"

  publish-docker-image:
    name: "Docker Image: Publish"
    permissions:
      contents: read
    needs: [build-image-linux-x86_64, build-image-linux-aarch64]
    runs-on: ubuntu-latest
    steps:
      - name: Set $USER if needed
        run: |
          if [ -z "$USER" ]; then
            echo "USER=runner" >> "$GITHUB_ENV"
          fi
      - run: sudo sysctl -w kernel.apparmor_restrict_unprivileged_userns=0
      - uses: actions/checkout@v6
      - uses: cachix/install-nix-action@v30
        with:
          nix_path: nixpkgs=channel:nixos-25.11
      - name: "Download: x86_64 image"
        uses: actions/download-artifact@v4
        with:
          name: docker-x86_64-linux.tar.gz
          path: /tmp/x86_64
      - name: "Download: aarch64 image"
        uses: actions/download-artifact@v4
        with:
          name: docker-aarch64-linux.tar.gz
          path: /tmp/aarch64
      - run: ls /tmp/x86_64 /tmp/aarch64
      - name: Publish docker image
        run: |
          nix develop .#ci --accept-flake-config -c publish-docker-image --impure
        env:
          IMAGE_NAME: wings
          QUAY_USERNAME: ${{ secrets.quay-username }}
          QUAY_PASSWORD: ${{ secrets.quay-password }}
          IMAGE_VERSION_MAJOR: ${{ inputs.major }}
          IMAGE_VERSION_MINOR: ${{ inputs.minor }}
          IMAGE_VERSION_PATCH: ${{ inputs.patch }}
          IMAGE_VERSION_PREREL: ${{ inputs.prerel }}
          IMAGE_ARCHIVE_x86_64: /tmp/x86_64/wings.tar.gz
          IMAGE_ARCHIVE_aarch64: /tmp/aarch64/wings.tar.gz
