name: CI Pipeline

concurrency:
  group: pipeline-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

on:
  merge_group:

  push:
    branches:
      - "main"

  pull_request:
    branches:
      - "main"
    types:
      - opened
      - synchronize

jobs:
  build-linux-x86_64:
    name: "Linux x86_64: Build"
    uses: ./.github/workflows/build.yml
    with:
      os: warp-ubuntu-latest-x64-2x
    secrets:
      cachix-token: "${{ secrets.CACHIX_AUTH_TOKEN }}"

  build-image-linux-x86_64:
    name: "Linux x86_64: Build"
    uses: ./.github/workflows/build.yml
    needs: [build-linux-x86_64]
    with:
      os: warp-ubuntu-latest-x64-2x
      target: image
    secrets:
      cachix-token: "${{ secrets.CACHIX_AUTH_TOKEN }}"
